spring.application.name=demo
spring.datasource.url=jdbc:postgresql://localhost:5432/demo
spring.datasource.password=demo
spring.datasource.username=demo
spring.datasource.driver-class-name=org.postgresql.Driver

# spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# Disable Swagger for Scalar
springdoc.swagger-ui.enabled=false

# Scalar
scalar.enabled=true
scalar.url=/v3/api-docs
scalar.path=/reference
scalar.pageTitle=Job Platform API Documentation

# Enable to diff the new schema for migrations
# spring.jpa.properties.javax.persistence.schema-generation.scripts.action=update
# spring.jpa.properties.javax.persistence.schema-generation.scripts.create-target=migration_diff.sql

# Flyway
spring.flyway.enabled=true

# Custom Props
auth.jwt.secret-key=djl5JEImRSlIQE1jUWZUalduWnI0dTd4QypGLUphTmRSZ1VrWHAyczV2OHkvQj9FKEcrS2JQZVNoVm1ZcQ==
