create table company (
    id integer generated by default as identity,
    hq_location varchar(255),
    name varchar(255),
    primary key (id)
);

create table engineer_skills (
    engineer_id integer not null,
    skill_id integer not null,
    primary key (engineer_id, skill_id)
);

create table engineer_profile (
    id integer generated by default as identity,
    bio varchar(255),
    github_url varchar(255),
    linkedin_url varchar(255),
    location varchar(255),
    primary key (id)
);

create table job_application (
    id integer generated by default as identity,
    applied_date timestamp(6),
    status smallint check (status between 0 and 3),
    engineer_id integer,
    posting_id integer,
    primary key (id)
);

create table job_posting (
    id integer generated by default as identity,
    description varchar(255),
    salary integer,
    title varchar(255),
    company_id integer,
    primary key (id)
);

create table posting_skills (
    posting_id integer not null,
    skill_id integer not null,
    primary key (posting_id, skill_id)
);

create table skill (
    id integer generated by default as identity,
    name varchar(255),
    primary key (id)
);

create table software_engineer (
    id integer generated by default as identity,
    name varchar(255),
    years_of_experience integer,
    profile_id integer,
    primary key (id)
);

alter table if exists software_engineer
    drop constraint if exists uk_software_engineer_profile_id;

alter table if exists software_engineer
    add constraint uk_software_engineer_profile_id unique (profile_id);

alter table if exists engineer_skills
    add constraint fk_engineer_skills_skill_id
    foreign key (skill_id)
    references skill;

alter table if exists engineer_skills
    add constraint fk_engineer_skills_engineer_id
    foreign key (engineer_id)
    references software_engineer;

alter table if exists job_application
    add constraint fk_job_application_engineer_id
    foreign key (engineer_id)
    references software_engineer;

alter table if exists job_application
    add constraint fk_job_application_posting_id
    foreign key (posting_id)
    references job_posting;

alter table if exists job_posting
    add constraint fk_job_posting_company_id
    foreign key (company_id)
    references company;

alter table if exists posting_skills
    add constraint fk_posting_skills_skill_id
    foreign key (skill_id)
    references skill;

alter table if exists posting_skills
    add constraint fk_posting_skills_posting_id
    foreign key (posting_id)
    references job_posting;

alter table if exists software_engineer
    add constraint fk_software_engineer_profile_id
    foreign key (profile_id)
    references engineer_profile;
