create table users (
    id integer generated by default as identity,
    username varchar(50),
    password char(60),
    enabled bool
);

create table authorities (
    username varchar(50),
    authority text
);
