create table users (
    id integer generated by default as identity,
    username varchar(50),
    password char(60),
    enabled bool,
    primary key (id)
);

create table authorities (
    username varchar(50),
    authority text
);
